In [2]:
import numpy as np

In [3]:
tensor=np.array([[[0,1,2],[3,4,5],[6,7,8]],[[00,11,22],[33,44,55],[66,77,88]]])
tensor

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 0, 11, 22],
        [33, 44, 55],
        [66, 77, 88]]])

In [4]:
tensor.ndim

3

## agregar o eliminar dimensiones

In [5]:
tensor=np.array([2,4,6], ndmin=5)
tensor

array([[[[[2, 4, 6]]]]])

In [7]:
expand=np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [14]:
print(tensor, tensor.ndim)
tensor_2=np.squeeze(tensor) #squeeze reduce las dimensiones que no estan en uso..
print(tensor_2, tensor_2.ndim)


[[[[[2 4 6]]]]] 5
[2 4 6] 1
